### ISSUE TITLE
compilers supported

### ISSUE THREAD

**Issue by GregKon** [joboccara/NamedType#35]
Hi

What compilers are supported? I have to tried compile tests with gcc 8.1.0 but does fails.

/Greg

**Comment by joboccara** [comment]
Hi Greg,

The oldest compilers currently supported are clang 3.9.0 and gcc 5.1. There was a compilation error on gcc, which I fixed with [this commit](https://github.com/joboccara/NamedType/commit/1d7035bba13b1e9938308f6f632fa719a1683407).
Thanks for bringing this up!

Cheers,
Jonathan
