### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by qchateau** [joboccara/NamedType#38]
I'm currently trying to have this library as part of the new [Conan Center Index](https://github.com/conan-io/conan-center-index/pull/1024), and it would be convenient to have a new tag for this library. It makes versioning easier and there has been plenty of improvements since the last tag.

**Comment by joboccara** [comment]
This should be done now, is the new tag ok for you?

**Comment by qchateau** [comment]
Thanks for the tag, I don't have time right now to add it to CCI but someone else might, now that NamedType is included in CCI it's pretty easy to add a new version to it
