### ISSUE TITLE
Windows MSVC Compile error with std::is_reference

### ISSUE THREAD

**Issue by Guillaume227** [joboccara/NamedType#4]
Hi Jonathan, [big fan of fluent c++, got to know you on cppcast]

I get this compile error with MSVC (Visual Studio 2017 15.3). That code is fine on gcc and clang.

> 	/NamedType/named_type.hpp(26): error C2512: 'std::is_reference<T_>': no appropriate default constructor available

`    explicit NamedTypeImpl(T&& value, typename std::enable_if<!std::is_reference<T_>{}, std::nullptr_t>::type = nullptr) 
`
while the following works (and to me looks more idiomatic):
`explicit NamedTypeImpl(T&& value, typename std::enable_if < !std::is_reference<T_>::value, std::nullptr_t > ::type = nullptr) : value_(std::move(value)) {}
`

Diff is just 
**std::is_reference<T_>{}**
becoming
**std::is_reference<T_>::value**

Would you accept a PR for that ?

**Comment by joboccara** [comment]
Yes, absolutely.
Sorry for the late reply, only saw your issue now.
Thanks!

**Comment by Guillaume227** [comment]
PR submitted: https://github.com/joboccara/NamedType/pull/5
