### ISSUE TITLE
Undesirable inclusion of `<iostream>` for freestanding compilers

### ISSUE THREAD

**Issue by Rb37** [joboccara/NamedType#57]
It is an undesirable to include `<iostream>` for freestanding compilers. This is especially true for embedded devices that do not have a `cout`. As you can see in this example [https://godbolt.org/z/8vrdv8](url) call to `std::ios_base::Init::Init()` cannot be optimized even if you dont use `cout` and even at maximum optimization level. But this is still add overhead by increasing compilation time, producing larger binaries and increasing startup time.

**Comment by CelticMinstrel** [comment]
Note: I think you only need `<ostream>` and not `<iostream>`. You might even be able to get away with just `<iosfwd>`.
