### ISSUE TITLE
Overhead?

### ISSUE THREAD

**Issue by kiliandys** [joboccara/NamedType#66]
Hi!
I am using strong types to return PixelColor (3 x uint8)  from a image cache library - that is used very intensively.
Is using strong type introducing runtime overhead?
Thank you!

**Comment by joboccara** [comment]
Hello,
Thanks for your interest in the NamedType library. You'll have to measure on your system, but the measurements I had made suggest there is not much overhead, read more [in this article](https://www.fluentcpp.com/2017/05/05/news-strong-types-are-free/).
